version: '3.8'

services:
  location-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location-service
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom"
      SPRING_PROFILES_ACTIVE: "prod"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
